// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfHg2zTp5OvK8NPGBvtAkM2a2_-_Nov4A',
    appId: '1:18828685223:web:c45d32c6e233885c789082',
    messagingSenderId: '18828685223',
    projectId: 'exam-37aa6',
    authDomain: 'exam-37aa6.firebaseapp.com',
    storageBucket: 'exam-37aa6.appspot.com',
    measurementId: 'G-VE7T05Q5PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLJS7-3dQ7KKvqBluKHRVGZdPBQldAy80',
    appId: '1:18828685223:android:4b39cb94f463f379789082',
    messagingSenderId: '18828685223',
    projectId: 'exam-37aa6',
    storageBucket: 'exam-37aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkbyzNvgXOK8RYqHVUDDaMHCUyJwGX_0',
    appId: '1:18828685223:ios:bd21b55e6f0cda4c789082',
    messagingSenderId: '18828685223',
    projectId: 'exam-37aa6',
    storageBucket: 'exam-37aa6.appspot.com',
    iosBundleId: 'com.example.flutterEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkbyzNvgXOK8RYqHVUDDaMHCUyJwGX_0',
    appId: '1:18828685223:ios:bd21b55e6f0cda4c789082',
    messagingSenderId: '18828685223',
    projectId: 'exam-37aa6',
    storageBucket: 'exam-37aa6.appspot.com',
    iosBundleId: 'com.example.flutterEducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfHg2zTp5OvK8NPGBvtAkM2a2_-_Nov4A',
    appId: '1:18828685223:web:c12f4f37ac7c08ac789082',
    messagingSenderId: '18828685223',
    projectId: 'exam-37aa6',
    authDomain: 'exam-37aa6.firebaseapp.com',
    storageBucket: 'exam-37aa6.appspot.com',
    measurementId: 'G-B6SLPMGK2K',
  );
}
